### ISSUE TITLE
[Android] Copy file to Download directory in android < 10

### ISSUE THREAD

**Issue by ErickLuizA** [RonRadtke/react-native-blob-util#170] opened 2022-06-25 03:11 UTC
Hello, 

Before anything, thank you very much for maintaining this library, I really appreciate your work.

At the moment, as far as I understand, the `MediaCollection.copyToMediaStore` method only truly copies the file to the shared Download directory if the android version is 10 or higher.

Am I wrong about that? Or is there a way to make that happen?
If not, do you have an idea of when this will be possible? Although I don't have much experience with native code, I am willing to help with anything necessary.

Thanks.

**Comment by RonRadtke** [comment] 2022-06-25 05:50
Hello,
thank you!

Exactly, the MediaCollection API is copying the file to the shared download folder for Android 10 and above.
For lower versions it's copying the file to the apps internal download folder.
You would need these two flags:
UIFileSharingEnabled
and
LSSupportsOpeningDocumentsInPlace

(See https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW20:~:text=3.2%20and%20later.-,UIFileSharingEnabled,-UIFileSharingEnabled%20(Boolean for more information)

**Comment by ErickLuizA** [comment] 2022-06-25 14:01
Hello,

Thanks for answering.

Is there any solution for android to work in a version lower than 10?

Is It possible to implement such functionality?

Using another API that can give access to the external storage when in a lower version or something like that?

**Comment by RonRadtke** [comment] 2022-06-26 08:13
It's possible yes.
Basically it's just a matter of the directory you're storing the files to.
The problem is currently we're not exporting the paths (see https://github.com/RonRadtke/react-native-blob-util/issues/89)
I am thinking about either offering a new variable like legacydirs which will return the external paths you need.
Will see if I can squeeze it in somewhen next week

**Comment by RonRadtke** [comment] 2022-06-27 13:09
I'm reopening for now.
I created a branch with changes to expose the old paths: https://github.com/RonRadtke/react-native-blob-util/tree/feature/legacypaths

Would be great if you're able to test it for your purpose. It's so far untested but I'll test it myself this or next week.

**Comment by ErickLuizA** [comment] 2022-06-28 02:03
Hello,

I have tested it here and it's working fine.

It would be cool if when the docs for these new changes are made, the need for runtime permissions is mentioned alongside it.

**Comment by RonRadtke** [comment] 2022-06-28 19:26
Thanks. But I sadly run into issues myself during testing, realizing that we will get warnings / errors if we try to build it with targetSDK > 29.
So I will have to find another way  for getting it to work for older versions.

But you could try using the downloadmanager option. This one should still work

**Comment by RonRadtke** [comment] 2022-07-01 20:07
Found a way around. Update will be released tomorrow

**Comment by RonRadtke** [comment] 2022-07-02 18:46
https://github.com/RonRadtke/react-native-blob-util/releases/tag/0.16.2

You can use the Mediastore API now also on old devices to store the file in the public downloads folder.
Or you do it manually, as you prefer.

**Comment by oman21** [comment] 2022-10-10 03:21
in android < 10 MediaCollection get this error

![This is an image](https://i.ibb.co/XymPKT9/2022-10-10-10-14-02.jpg)

**Closed** 2022-11-05 21:05 UTC
Labels: question
