### ISSUE TITLE
MediaStore to use common downloads directory of android

### ISSUE THREAD

**Issue by anshul0410** [RonRadtke/react-native-blob-util#62] opened 2021-09-02 11:48 UTC
Hi, thanks for maintaining this project. i have more of a query than a bug to report.
i'm using version 0.13.8 of this library and implementing scope storage related updates in my RN app.
Is there a way to download files directly to common download path for android, currently file download is happening in app specific internal storage, which might not be very intuitive for users in general.
Is there a plan to implement MediaStore API to make use of download path, or is there any other solution to do so?
Any help or suggestion is much appreciated.
Thanks.

**Comment by RonRadtke** [comment] 2021-09-02 14:18
Hi @anshul0410,
at the moment there is no possibility.
But I am currently working on integrating it in the lib.  It's the next feature for the lib and it is already in work :)
But I don't know when it will be done yet

**Comment by RonRadtke** [comment] 2021-10-16 15:36
Just wanting to give you a short update.
I have the very basics working now (creating and writing data to media files), but there is still a lot of work to do.
Especially to be able to use fileCache and such things.

**Comment by afilp** [comment] 2022-01-26 20:38
@RonRadtke Is there any workaround until the solution is fully implemented? An app needs the invoices to be downloaded in a non-app specific folder, like "Downloads" or "Documents" and we are not sure how we can implement this without your upcoming solution. Thanks!

**Comment by RonRadtke** [comment] 2022-01-27 13:38
@afilp in general it is working.
The basics are done.  So saving a file to downloads works.

But I had / have plenty of private issues eating up my time the last moths. So I didn't get to do the work on all the nice-to-have and testing like I would want to in order to make a release for it.

What doesn't work yet:
- opening the file after saving it
- storing the file without using fileCache
- all the functionality around storing files like renaming / moving / copy /delete / ....

If you change to the feature/media_collections branch you could save a file by using the following code snippet.
It's just copied from my testing app, so you might have to adjust variable names etc :)
```
    ReactNativeBlobUtil
            .config({
                fileCache: true
            })
            .fetch('GET', targeturi, {'Accept': 'application/octet-stream'}, JSON.stringify(dat))
            .then(async (res) => {
                let pathnew = await ReactNativeBlobUtil.MediaCollection.createMediafile({name: filename, parentFolder: '', mimeType: get_mimetype_for_file(filename)}, 'Download');
                await ReactNativeBlobUtil.MediaCollection.writeToMediafile(pathnew, res.path());
});
```

**Comment by damian-balas** [comment] 2022-01-27 15:39
@RonRadtke Well it would be fine for me if you release a version where we can only download files to that dir. :)

**Comment by damian-balas** [comment] 2022-01-27 17:26
@RonRadtke Would you also provide a snippet for iOS? I can't make it work... It gives me success status, but there are no files in the `File.app`. I need to have it physically on the users phone so he can access it anytime.

**Comment by RonRadtke** [comment] 2022-01-27 17:52
@damian-balas iOS does not use the android mediaStore.
For iOS you need
````
ReactNativeBlobUtil
            .config({
                fileCache: true
            })
            .fetch('GET', targeturi, {'Accept': 'application/octet-stream'}, JSON.stringify(dat))
            .then(async (res) => {
                await ReactNativeBlobUtil.fs.appendFile(destPath, res.path(), 'uri');
})
````

So for now you will ahve to put in a switch based on `` Platform.OS==='android'``

**Comment by afilp** [comment] 2022-01-27 18:55
@RonRadtke Thanks a lot Ron! For me, just being able to download a PDF to the common `Downloads` or `Documents` folder would be sufficient.

Do we need to have conditionals before the call or the following code will work? (for both iOS and Android?)

I used to have this code in the main `config`, so I thought the iOS would be OK because of the `path` there:
`        appendExt: 'pdf',
        fileCache: true,
        path: destPath,
`

```
  let dirs = ReactNativeBlobUtil.fs.dirs;
  const dirToSave = Platform.OS === 'ios' ? dirs.DocumentDir : dirs.DownloadDir;
  console.log('dirToSave', dirToSave);
  const destPath = dirToSave + '/Invoice_' + paymentId + '.pdf';

  // const date = new Date();
  const { data } = await new Promise((resolve, reject) => {
    try {
      ReactNativeBlobUtil.config({
        appendExt: 'pdf',
        fileCache: true,
        path: destPath,
        addAndroidDownloads: {
          path: destPath,
          /*        destPath:
          dirs.DownloadDir +
          '/Invoice_' +
          Math.floor(date.getTime() + date.getSeconds() / 2),*/
          useDownloadManager: true,
          title: 'Invoice ' + paymentId,
          description: 'Invoice PDF',
          mime: 'application/pdf',
          mediaScannable: true,
          notification: true,
        },
      })
        .fetch('GET', `${window.our.BASE_URL}/payment?paymentId=${paymentId}`, {
          Authorization: `Bearer ${token}`,
          Accept: 'application/pdf',
          'Content-Type': 'application/pdf',
        })
        .progress((received, total) => {
          console.log('progress', received / total);
        })
        .then(async res => {
          console.log('The file saved to ', res.path());
          Alert.alert(t('invoiceDownloaded'));
          if (Platform.OS === 'ios') {
            await ReactNativeBlobUtil.fs.appendFile(
              destPath,
              res.path(),
              'uri',
            );
            ReactNativeBlobUtil.ios.openDocument(res.path());
          } else {
            const android = ReactNativeBlobUtil.android;
            android.actionViewIntent(
              res.path(),
              'application/pdf',
              'Choose app to preview',
            );
          }
          resolve(res);
        })
        // Something went wrong:
        .catch((errorMessage, statusCode) => {
          console.log(errorMessage);
          reject(errorMessage);
        });
    } catch (err) {
      console.log(err);
      reject(err);
    }
  });
```

**Comment by damian-balas** [comment] 2022-01-27 19:11
> @damian-balas iOS does not use the android mediaStore. For iOS you need
> 
> ```
> let destPath = ReactNativeBlobUtil.fs.dirs.DocumentDir + '/' + filename;
> ReactNativeBlobUtil
>             .config({
>                 fileCache: true
>             })
>             .fetch('GET', targeturi, {'Accept': 'application/octet-stream'}, JSON.stringify(dat))
>             .then(async (res) => {
>                 await ReactNativeBlobUtil.fs.appendFile(destPath, res.path(), 'uri');
> })
> ```
> 
> So for now you will have to put in a switch based on ` Platform.OS==='android'`. Downloaddir on iOS doesn't work since there is no download folder like on android.

Thanks for your feedback. I'm aware of this, but my issue is that I can't see the downloaded file in the native File app. It's empty.

this is my code:

```
export const downloadPdf = async ({ url, filename }) => {
  let response;
  const newFilename = `${filename}-${Date.now()}`;
  if (!url || typeof url !== 'string') {
    throw new Error('Link do pliku PDF jest niepoprawny!');
  }

  try {
    if (Platform.OS === 'ios') {
      response = await downloadForIOS({ filename, url });
    } else {
      response = await downloadForAndroid({ filename, url });
    }

    showSuccessToast({
      text: `${newFilename}.pdf został pobrany pomyślnie!`, // TODO: translate this!
    });
  } catch (error) {
    showErrorToast({
      error: {
        message: `Nie udało się pobrać ${newFilename}.pdf. Spróbuj jeszcze raz.`, // TODO: translate this!
      },
    });
    Logger.error(error);
  } finally {
    if (response?.flush) {
      // response.flush();
    }
  }
};

const downloadForAndroid = async ({ filename, url }) => {
  const result = await request(PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE);

  if (result !== RESULTS.GRANTED) {
    throw new Error(result);
  }

  const response = await ReactNativeBlobUtil.config({
    fileCache: true,
  }).fetch('GET', url);

  const newPath =
    await ReactNativeBlobUtil.MediaCollection.createMediafile(
      {
        name: `${filename}.pdf`,
        parentFolder: '',
        mimeType: 'application/pdf',
      },
      'Download',
    );

  await ReactNativeBlobUtil.MediaCollection.writeToMediafile(
    newPath,
    response.path(),
  );

  return response;
};

const downloadForIOS = async ({ filename, url }) => {
  const path = ReactNativeBlobUtil.fs.dirs.DocumentDir + '/' + filename;
  const response = await ReactNativeBlobUtil.config({
    fileCache: true,
  }).fetch('GET', url);

  await ReactNativeBlobUtil.fs.appendFile(path, response.path(), 'uri');
  return response;
};
```

**Comment by RonRadtke** [comment] 2022-01-27 19:51
The lib currently doesn't support the option to save it to files app.
But you can set
UIFileSharingEnabled 
and
LSSupportsOpeningDocumentsInPlace
To yes in yours app plist file. (Just take the link below and search for the first entry, there it is explained that itit should work... can't get a working link tonit on the phone sorry,)
Or see https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW37

**Comment by damian-balas** [comment] 2022-01-27 19:52
Thanks! 
Made it work with this code:

```
const downloadForIOS = async ({ filename, url }) => {
  const path =
    ReactNativeBlobUtil.fs.dirs.DocumentDir + '/' + filename + '.pdf';
  const response = await ReactNativeBlobUtil.config({
    fileCache: true,
    appendExt: 'pdf',
    path,
  }).fetch('GET', url, {
    Accept: 'application/pdf',
    'Content-Type': 'application/pdf',
  });

  ReactNativeBlobUtil.ios.previewDocument(path);
  return response;
};
```

But... the user needs to click: `Save to Files` button :)

**Comment by RonRadtke** [comment] 2022-01-27 21:20
@afilp 
Sorry just saw your post now.
In general you should be able to use the config, just that the ``useDownloadManager`` might make problems, and the rest of the fields would not be respected by the write method for the mediastore.
And ofc you'll have to exchange the methods for writing the file on android.
So for your else part you need a `` await ReactNativeBlobUtil.fs.appendFile(destPath, res.path(), 'uri');``. The actionViewIntent does not work yet, as stated, not sure what the problem is. 

I will fix it in a way that the config will be used. But currently I won't have the time for that.

@afilp @damian-balas 
And as soon as the config works and the opening of the files works I'll make a release for and by that push the version to 0.14.x
If anyone of you has some time to help / test I would be very glad about it

**Comment by afilp** [comment] 2022-01-27 23:03
@RonRadtke Thank you for your efforts!

I tried everything and still the file goes to the app's sandboxed storage and not to a common documents folder (note: I am not using your special branch, should I?). 
I tried to make it work with your advice to check these 2 properties in plist to `true`:
![image](https://user-images.githubusercontent.com/7850073/151457633-e5605246-0c24-4310-b4b6-3741e1ebae4b.png)

But still, res.path() and destpath are exactly the same, the app's one:
![image](https://user-images.githubusercontent.com/7850073/151457547-896bb150-3e83-4966-914c-fa78472cf0c2.png)

I tried all combinations, even having `fileCache: false,`, still it does not work.

Also, this code only works once per session, it never works again for the next download:
`ReactNativeBlobUtil.ios.openDocument(res.path());`

Thanks a lot or all your efforts!

**Comment by RonRadtke** [comment] 2022-01-28 09:35
That's how storage in iOS works.
Apps can only ever write in the sandbox storage.
The only possibility you have is either saving it to the file app as you pointed out.
The option I pointed out (setting the two flags) will make the files browsable by the files app and thus leads to the files show up in the files app. That's basically the only option you have if you don't want the user to have to save it again.

**Comment by damian-balas** [comment] 2022-01-28 09:44
> That's how storage in iOS works. Apps can only ever write in the sandbox storage. The only possibility you have is either saving it to the file app as you pointed out. The option I pointed out (setting the two flags) will make the files browsable by the files app and thus leads to the files show up in the files app. That's basically the only option you have if you don't want the user to have to save it again.

Is is secure to make those files visible?

**Comment by RonRadtke** [comment] 2022-01-28 10:09
> Is is secure to make those files visible?

In general yes. Of course it is your responsibility to make sure there is no info available the user should not be able to access, like config files. Same it is your responsibility to make sure you don't store any malware etc there. But it is in general fine to use, the official developer docu of apple is describing it explicate so we can use it, it's not a hack or sth like that.

**Comment by afilp** [comment] 2022-01-28 18:50
@RonRadtke Sorry if this is irrelevant, i am using `react-native-image-picker`, how could I create a video file from this uri inside the same folder with the others? With `appendFile`? Thank you!

![image](https://user-images.githubusercontent.com/7850073/151604434-c85122e0-36af-43c2-af15-2495e92596db.png)

**Comment by RonRadtke** [comment] 2022-01-28 20:57
where did you get the file from?
It looks like it is a file from mediastore. Currently the library can't do anything with such URIs in means of loading the file to store it somewhere else e.g.

**Comment by afilp** [comment] 2022-01-29 09:18
I used `react-native-image-picker` and I just picked a video file. The `type` and `data` are what I get as a response (among other fields such as `size`, `duration`, etc. that I do not need to upload in the form.

**Comment by RonRadtke** [comment] 2022-01-29 11:11
No currently not.
The content URI is indicating that it is an uri from a content provider. So it's not a path it is a reference to a certain file.
Basically you need to use a contentResolver and get the InputStream from that one, and with that stream you can write the file in the app specific directory. (Some MediaStore magic)
And that is currently not implemented.

I know who to set a method up to do what you need. But I won't have time to do so until maybe Monday.

**Comment by afilp** [comment] 2022-01-29 11:56
@RonRadtke Thanks a lot for your feedback.

We have an app in the store and Android (only) users cannot upload the "picked" videos, so if we could have a solution by Monday that would be great indeed!

Please note that I am not particularly interested to "copy" the video file to the "app-specific" folder (this was just a suggestion), I am interested for `react-native-blob-util/`  to just upload the file no matter where it is located, or whether it is a "content" or a "file" one. Of course, if intermediate custom steps are needed to be programmed by us (for example copying something somewhere), please let us know and we will do!

Thanks a lot!

**Comment by RonRadtke** [comment] 2022-01-29 12:12
Well, I can't promise I get it done on Monday. Depends a lot on how much spare time I'll have and how much I have to work / family.
But I'll try.

Of course it would be possible without that intermediate step too. But I would like to have it as a separate module and don't mess the library up too much by having every functionality everywhere. 
Besides, on modern phones copying a single file really shouldn't be an issue storage wise.

**Comment by afilp** [comment] 2022-01-29 16:20
Yes Ron, I understand.

FYI, I tried to do an `fs.copyFile` logic and I have reached a wall...

```err Error: Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/video:45772 from pid=20415, uid=10641 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs```

The code I am using is this:

```
if (type === 'video' && Platform.OS === 'android') {
      let dirs = ReactNativeBlobUtil.fs.dirs;
      const dirToSave =
        Platform.OS === 'ios' ? dirs.DocumentDir : dirs.DownloadDir;
      try {
        console.log('dirToSave', dirToSave);
        const destPath = dirToSave + '/' + filename + '.' + typeForTheFilename;

        debugger;
        await fs.copyFile(decodeURIComponent(el.uri), destPath);
      } catch (err) {
        console.log('err', err);
      }
      const res = await fs.readDir(dirToSave);
      debugger;
      console.log('res', res);
    }
    ```

**Comment by afilp** [comment] 2022-01-29 16:52
I updated the code and I see that I do get `true` for the `READ_EXTERNAL_STORAGE` permission, so in theory I do have permission to read the file from there (or not?).

![image](https://user-images.githubusercontent.com/7850073/151669668-30cc679d-7eab-4aae-92ec-71300177e7b8.png)

**Comment by afilp** [comment] 2022-01-29 17:28
These are the Android permissions, I even added the "MANAGE_DOCUMENTS" to no avail:

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <uses-permission android:name="android.permission.MANAGE_DOCUMENTS" />

**Comment by RonRadtke** [comment] 2022-01-29 19:58
No you don't. Because the file does not belong to your app.
I would recommend reading a bit about scoped storage.
Basically by default you can only read / write within the scoped storage belonging to your app. And only your app, no other app and neither the user itself, has access to these files.
So if you want access to a file somewhere else (e.g. in the images/videos in the gallery) first of all the user has to select the file actively (you can't just query a random file, except with file manager permissions) , and then you need to use certain functions to be allowed to read these files.

They changed the whole storage system with Android 10, you still have the "old" system in mind.
But that's all the magic happening in java / kotlin you usually don't see when just programming your app in react-native.

**Comment by afilp** [comment] 2022-01-29 20:33
Thanks Ron, so the problem with the "content" file will still be there unless you find a way for all of us to be able to get it as an actual file inside the app's scoped storage. I wish `react-native-image-picker` had an option for us to save the actual file instead of providing a "content" link.

Meanwhile, I managed to write to the common "Downloads" folder using `react-native-file-access`, which is the opposite direction (I needed this in order to be able to save a downloaded PDF there, using their `fetch`). I wonder if this could be used somewhere in your library.

Thanks a lot!

**Comment by RonRadtke** [comment] 2022-01-29 20:40
@afilp to the downloads folder you can save with my library on the new branch...
So there is no need for the additional library.

**Comment by afilp** [comment] 2022-01-29 20:59
No you misunderstood me. They are 2 different problems. 

I still have the major problem of "content" video files not being able to be uploaded to our server, because there is no way at the current master branch to get the actual file from a "content" uri.

My initial asking about saving to Downloads also still remains. I only mentioned the other library as I found it just 2 hours ago and gave it a try in case there is something there that my help you with the implementation/testing of your branch.

Thanks a lot..

**Comment by RonRadtke** [comment] 2022-01-29 21:20
Okay, thanks. Might help with my problem, that I have to use the cache file, but will see.

I wrote a new function copyToInternal which should do the work and copy the file to the apps internal storage. Just need to specify the contenturi and the targetpath.
But it is untested and I don't have time to test it right now. So feel free to test it  :D Otherwise I might get to it tomorrow or on monday.

**Comment by afilp** [comment] 2022-01-29 22:55
Thanks a lot Ron, you are awesome! 

The copyToInternal function can be used to also get the video file from the "content" uri in media store (in the format the picker gives) and upload it? 

Or this is only for solving the initial problem with the "downloads"?

**Comment by RonRadtke** [comment] 2022-01-30 08:03
@afilp 
Yes to the first.
This function will copy a file given by content URI (so the video you get from ``react-native-image-picker``) to the apps internal storage.
And after that being done you can use it like every other file in the apps storage (so like the images you get from ``react-native-image-picker``), and thus should be able to upload it.
So:
1) pick the image
2) copy it with ``await ReactNativeBlobUtil.MediaCollection.createMediafile(<contenturi>, <internal targetpath>)``
3) send it to the sever as usual

WIth <internal targetpath> being e.g. ``ReactNativeBlobUtil.fs.dirs.CacheDir``

Saving to dowloads works too.
For that you need sth like the following:
````
    ReactNativeBlobUtil
            .config({
                fileCache: true
            })
            .fetch('GET', targeturi, {'Accept': 'application/octet-stream'}, JSON.stringify(dat))
            .then(async (res) => {
                let pathnew = await ReactNativeBlobUtil.MediaCollection.createMediafile({name: filename, parentFolder: '', mimeType: get_mimetype_for_file(filename)}, 'Download');
                await ReactNativeBlobUtil.MediaCollection.writeToMediafile(pathnew, res.path());
});````

Explanation:
``ReactNativeBlobUtil.MediaCollection.createMediafile(...)`` will create a new MediaStore file with the given name / subfolder / ...
``ReactNativeBlobUtil.MediaCollection.writeToMediafile`` will write the data from the fileCache (so res.path()) into the new media storage file
So with these two function calls after the fetch resolved you're able to write the file to the public downloads folder.

**Comment by afilp** [comment] 2022-01-30 09:11
Thanks @RonRadtke 

Meanwhile, I read a lot for a possible workaround and found a post that said the he used `stat` and just took the actual file uri through this. I tried it and it did work (i.e. the actual video did upload):

```
        const stat = await ReactNativeBlobUtil.fs.stat(el.uri);
        el.uri = stat.path;
```

Was that just a lucky coincidence? Maybe because it was in `Movies`?

![image](https://user-images.githubusercontent.com/7850073/151693683-4ef513a3-8404-4b7c-8b80-65574b679a8d.png)

I wonder if this can be a solution or it will fail in many other cases.

Thanks.

**Comment by RonRadtke** [comment] 2022-01-30 11:09
@afilp it works, but it might fail. A URI doesn't necessarily has to be a file or anything you can read or use. So it might work for all your cases since you come over the picker. But in general it is something that will sooner or later break.
An other possibility that would likely would work would be to return a BLOB object containing the data of the file - that would skip the copy part too.
But copying will do the cut for now too.
Regardless getting the BLOB or so would be a nice feature in general.

So if you don't have a problem with, I would say we stick with the copying for now. At least that is the fastest way you will be able to use that functionality, since I don't have that much time currently (exams, work, family, ...)
And I will keep working on the mediastore, add a few more functions and then release it officially. But till then, you can use the branch.

**Comment by alariej** [comment] 2022-01-30 15:00
Very interesting discussion. Thanks @RonRadtke for working on this repo. I ended up here as I am also facing the issue of saving files to the shared "Download" folder.

With the old package, I was simply using `RNFetchBlob.fs.dirs.DownloadDir` (which returned `/storage/emulated/0/Download`) as the target folder, and then copying (with `RNFetchBlob.fs.cp(sourcePath, targetPath)`) files from the cache to the target.

In this package, `ReactNativeBlobUtil.fs.dirs.DownloadDir` returns `/storage/emulated/0/Android/data/<myapp>/files/Download`. After reading the comments here and in other forums, I was under the impression that this change was motivated by some change in the Android API, which would not allow to save to the shared Download folder anymore.

So I just quickly tested hardcoding the target to `/storage/emulated/0/Download` and tried copying files from the cache to the target. It worked both on a physical device running Android 9, and on an emulator (Pixel 5) running Android 11.

So I am not quite sure why `ReactNativeBlobUtil.fs.dirs.DownloadDir` doesn't return `/storage/emulated/0/Download` as before. Am I misunderstanding something?

Note: I just use the standard permissions READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE in the manifest.

**Comment by RonRadtke** [comment] 2022-01-30 15:59
This should not work unless you're using ``preserveLegacyExternalStorage=true``.
It was changed because the way to aquire the paths was changed. The old methods ate flagged deprecated and the new return other values.
It came with one of the PRs I mergred after taking over the lib. But it is in general not possible to write there anymore, especially since the flag mentioned only works on targetapilevel < 30.
But as mentioned in one PR there would be the possibility to add a flag to get the old paths. Even though it won't help anyone targeting Android 11 (api 30), which is mandatory for all updates by now.

**Comment by alariej** [comment] 2022-01-30 17:39
Oh you're right, I do have `android:requestLegacyExternalStorage="true"` in the manifest. So I guess the MediaStore API is the best way to go from now on.

**Comment by RonRadtke** [comment] 2022-01-31 15:51
@afilp so copying to the app storage works. So basically all functionality you need is available on the feature branch.
I also managed to fix the issue with opening a file downloaded to the downloads folder, so we're getting closer for a release - at least if we skip the whole part in the config with overwrite / fileCache=false / ....

**Comment by afilp** [comment] 2022-01-31 17:18
Excellent! I am looking forward to the release and use it asap!

Also, remember that I tried meanwhile to solve the problem of just copying to a "public" folder with another library?

See here, while it works in Android, I have a problem in iOS, it still tries to write in a "non-public" (app-specific) Downloads folder.
https://github.com/alpha0010/react-native-file-access/issues/41

I am only mentioning it, so that you get inspired of the issue and maybe your branch solves this problem too. Thanks!

**Comment by RonRadtke** [comment] 2022-02-01 08:14
@afilp as explained already. It's not possible.
The only option to offer would be an action for the user to save it manually by himself. But there the user probably would also see all other options about sharing the file.

**Comment by afilp** [comment] 2022-02-01 09:20
Sorry I have not realized this well, so the only way is to use the `Share` method of react-native and hope that uses will find the "Save" option.

**Comment by RonRadtke** [comment] 2022-02-01 09:24
Yes, at least if you want it saved there and are not fine with it being shared and thus be visible there.
I don't understand why you want to explicitly store it in downloads / documents and not just show it there. The user won't see the difference.

**Comment by afilp** [comment] 2022-02-01 11:01
@RonRadtke Maybe I get this wrong, but when `react-native-blob-util` downloads the PDF then we show an alert that says something like "PDF Downloaded". But then the user has no clue what to do next to get to the actual file. I wonder if there is a way to have a link to that particular folder in the `FIles` app, so that the `Files` app opens in that folder for the user to view the file immediately.

**Comment by RonRadtke** [comment] 2022-02-01 13:16
@afilp there are basically two options:
- Tell the user he will find it in the documents folder (if you have sharing active and save it to the documents folder)
- Open the file for the user with `` ReactNativeBlobUtil.ios.openDocument(destPath)``

**Comment by afilp** [comment] 2022-02-01 13:29
I did use both the  `previewDocument` and the `openDocument`, like that:
```
if (Platform.OS === 'ios') {
            ReactNativeBlobUtil.ios.previewDocument(res.path());
          }
          ```
          
However, it only works the first time during the entire app's session. It does not appear the next times I download a document, the same or others. Is this a bug I assume? Have you noticed this behavior? I do not know why this happens.

**Comment by RonRadtke** [comment] 2022-02-01 13:31
Yes that is for sure a bug. 
If there is no issue yet, could you please create one for? So we don't have too much of a mess in this one here

**Comment by afilp** [comment] 2022-02-01 13:44
Sure, here it is:
https://github.com/RonRadtke/react-native-blob-util/issues/108

**Comment by alariej** [comment] 2022-02-01 21:10
For info, I decided to go ahead for now with the `cpExternal(soucePath, destPath, dirType)` function from https://github.com/alpha0010/react-native-file-access, which uses the MediaStore API. _dirType_ can be 'downloads', 'images', 'audio' or 'video'.

It pretty much fits my app's use case since user files are already downloaded and in the cache, and just need to be copied and made available outside of the app. Would be great if _react-native-blob-util_ eventually had a similar function.

**Comment by RonRadtke** [comment] 2022-02-02 08:48
@alariej yep, is planned for this or next week :)

**Comment by afilp** [comment] 2022-02-04 14:07
> Thanks @RonRadtke
> 
> Meanwhile, I was reading a lot about this issue as many other users face it with `pickers` and found a post that said the he used `stat` and just took the actual file uri through this. I tried it and it did work (i.e. the actual video did upload):
> 
> ```
>         const stat = await ReactNativeBlobUtil.fs.stat(el.uri);
>         el.uri = stat.path;
> ```
> 
> Was that just a lucky coincidence? Maybe because it was in `Movies`?
> 
> ![image](https://user-images.githubusercontent.com/7850073/151693683-4ef513a3-8404-4b7c-8b80-65574b679a8d.png)
> 
> I wonder if this can be a solution (no need to copy anything) or it will fail in many other cases/devices/Android versions/etc,
> 
> Thanks.

@RonRadtke I just tried it in a tablet, picking (with `image-picker`) an mp4 video from the `Downloads` folder which I downloaded previously from Google.

I get this error, is there any way to solve this?

![image](https://user-images.githubusercontent.com/7850073/152541896-ffd3f1e2-dd2f-4803-932b-b533c487f28c.png)

**Comment by afilp** [comment] 2022-02-04 16:56
The strange thing is that the behavior is different (it works) in my Android phone, while both have Android 11 version.

I assume they have a different way to store the "Downloaded from Google" video file.

**Comment by RonRadtke** [comment] 2022-02-05 21:20
@afilp it's released!

The issue with stat is what I described earlier. There is no guarantee for the row actually pointing to a file. And the issue you're seeing here is exactly that. There is no way to solve that except for switching to the newly introduced APIS

**Comment by RonRadtke** [comment] 2022-02-05 21:21
I'll reopen the issue again - just in case you have feedback.
If there are any new bugs - please create a new issue though

**Comment by afilp** [comment] 2022-02-06 15:43
Thanks Ron!

Maybe you missed to type the `row` here?

![image](https://user-images.githubusercontent.com/7850073/152688801-e6a838f3-183d-419a-9554-dd4aee673d0f.png)

**Comment by afilp** [comment] 2022-02-06 15:52
> @afilp it's released!
> 
> The issue with stat is what I described earlier. There is no guarantee for the row actually pointing to a file. And the issue you're seeing here is exactly that. There is no way to solve that except for switching to the newly introduced APIS

With your new v0.14 we do not need to do anything else other than use it, correct? Not sure what you meant with `switching to the newly introduced APIS`. This is done on v0.14, correct? Or we have to manually do something more? Thanks!

**Comment by afilp** [comment] 2022-02-06 17:29
Also, I tried to update the Wiki but I do not have update permissions:

From:
`let destpath = ReactNativeBlobUtil.dirs.CacheDir`

To:
`let destpath = ReactNativeBlobUtil.fs.dirs.CacheDir`

(there is a missing `fs` there, I believe)

Maybe you would like to change this.

**Comment by RonRadtke** [comment] 2022-02-06 20:31
> Thanks Ron!
> 
> Maybe you missed to type the related `code` here?
> 
> ![image](https://user-images.githubusercontent.com/7850073/152688801-e6a838f3-183d-419a-9554-dd4aee673d0f.png)

no, that's exactly want I meant to write. You get a database row (or multiple) from a query. But probably it would be better to write cursor instead of row, since we get a cursor not a single row.



> > @afilp it's released!
> > The issue with stat is what I described earlier. There is no guarantee for the row actually pointing to a file. And the issue you're seeing here is exactly that. There is no way to solve that except for switching to the newly introduced APIS
> 
> With your new v0.14 we do not need to do anything else other than use it, correct? Not sure what you meant with `except for switching to the newly introduced APIS`. This is done on v0.14, correct? Or we have to manually do something more? Thanks!

You need to use the new functionality. it's not a replacement for the old one, it's an addition. So you will have to call the correct functions as described in the wiki.

**Comment by afilp** [comment] 2022-02-06 22:38
Ι tested it in both my Android phone and tablet and worked perfectly! 

Thanks a lot!

**Comment by jaedontym** [comment] 2022-02-07 04:04
Hi @RonRadtke, thank you for working so actively on this library. It's been really useful for developers like me who aren't familiar with native Android code. You have no idea how happy I was to see v0.14 released this morning!

On that note, I've been trying to get v0.14 to work on Android 7 but I'm having issues. I'm thinking one of the issues might be in this method from `ReactNativeBlobUtilMediaCollection.java` (added my questions as comments in the code):

```
public static Uri createNewMediaFile(FileDescription file, MediaType mt) {
    ...

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
     ...
    } else {
        File directory = Environment.getExternalStoragePublicDirectory(relativePath);
        if (directory.canWrite()) {
            File f = new File(relativePath + '/' + file.getFullPath()); // <-- Instead of relativePath, should it be directory.getPath() instead? Right now this seems to be causing the createNewMediaFile method to return null
            if (!f.exists()) {
                boolean result = f.mkdirs(); // <-- Should this be f.createNewFile() instead? Right now it's creating a folder
                if (result) return Uri.fromFile(f);
            }

        }
    }

    return null;
}
```

I tried replacing making the following replacements and the file got created successfully in the public downloads folder:
- `directory.getPath()` instead of `relativePath`
- `f.createNewFile()` instead of `f.mkdirs()`

However this led to another problem in the `writeToMediaFile()` method:

![Screenshot 2022-02-07 at 11 22 23 AM](https://user-images.githubusercontent.com/80374392/152721232-0dfedfeb-7a5d-4c0e-8211-3f104c579016.png)

Here's a relevant snippet of my React Native code:
 ```
   ReactNativeBlobUtil
      .config({
        fileCache: true,
        path: `${Platform.OS === 'ios'
          ? ReactNativeBlobUtil.fs.dirs.DocumentDir
          : ReactNativeBlobUtil.fs.dirs.DownloadDir
        }/${filename}`,
      })
      .fetch('GET', url, {...})
      .then(async (res) => {
        if (Platform.OS === 'ios') {
          ...
        } else {
          const result = await ReactNativeBlobUtil.MediaCollection.copyToMediaStore(
            {
              name: 'TestFile',
              parentFolder: '',
              mimeType: 'application/pdf',
            },
            'Download',
            res.path(),
          );
        }
      });
```

I'm not sure if this is considered a new bug. If it is, I'll create a new issue as requested.

**Comment by RonRadtke** [comment] 2022-02-07 22:08
Hi @jaedontym,
thank you very much for appreciating my work here. It really helps to now people do like and sue my work.
And thanks for the bug report.
You're partly right.
I absolutely forgot to actually create the file. I'm currently only creating the parent directories, but we have to create these too, we can't just only create the file. This will otherwise lead to an error if the parent directory doesn't exist.
I am working on a fix for it, I just want to test it first since I did some more clean up and  adding that the write method works for older APIs too.

**Comment by jaedontym** [comment] 2022-02-08 01:47
@RonRadtke Thank you so much. Can't wait to integrate the updates to get my app working properly with the newer Android versions! 
I'll continue reporting relevant bugs here as I find them :)

**Comment by afilp** [comment] 2022-02-08 19:01
@RonRadtke Just to make sure, the picker store in the "Cache", right? So this gets bigger and bigger? Or is it automatically cleaned when closing the app, etc.?

I asking in case I have to manually delete the selected images/videos after the user uploads them to the server, using `react-native-blob-util`.

If yes, I should use this method of yours?  `ReactNativeBlobUtil.fs.mv`

Thanks!

**Comment by RonRadtke** [comment] 2022-02-09 20:34
Yes that will grow. Unlink would be the way to go.

**Comment by HagarAyad** [comment] 2022-02-10 12:46
I'm facing problem with copyToMediaStore , I get this error : Failed to get output stream
 here is my code 
 const result =
              await ReactNativeBlobUtil.MediaCollection.copyToMediaStore(
                {
                  name: eventTitle, 
                  parentFolder: '', 
                  mimeType: 'application/pdf', // MIME type of the file
                },
                'Download', 
                `${filePath}`,
              );
and filePath is : /storage/emulated/0/Android/data/com.runofshow/files/Download/Test.pdf

**Comment by afilp** [comment] 2022-02-10 20:15
> Yes that will grow. Unlink would be the way to go.

I did not see in the docs what type is the response data, is it always a boolean? I am using JSON.parse as I though it can also be an object and I need to return it back to react-query:

![image](https://user-images.githubusercontent.com/7850073/153489018-7b786763-4594-4001-87fa-89d696fb6664.png)

So, what should we expect for "data" there? Thanks!  (on uploading success I mean)

**Comment by afilp** [comment] 2022-02-10 20:19
What type is the response data, is it always a boolean? 
I am using JSON.parse as I though it can also be an object and I need to return it back to react-query:

![image](https://user-images.githubusercontent.com/7850073/153489018-7b786763-4594-4001-87fa-89d696fb6664.png)

So, what should we expect for "data" there? Thanks!  (on uploading success I mean)

**Comment by RonRadtke** [comment] 2022-02-10 21:05
> UPDATE: I do see the photo in the UI, but when trying to re-upload it it shows as missing. So why the UI shows it while it is not there?

Which UI?

> So, what should we expect for "data" there? Thanks! (on uploading success I mean)

Whatever your server sends. The data is the raw value your server is sending, or, if your config is specifying to store it in a file, the path.
So depending on what your goal is, it might be better to use the ``text()`` or ``json()`` since this will resolve a file path and return the data sent by the server.

**Comment by jaedontym** [comment] 2022-02-21 03:44
@RonRadtke Hi Ron! How are the fixes coming along? I hope that no additional complications arose 😰  
I went ahead with the app internal storage implementation first but this is affecting the UX of downloading and uploading files quite a bit (most users don't know how to navigate to the directory). Fortunately that's not the app's main feature but I do hope to be able to get this sorted out in time.

As always, really appreciate your work to keep `rn-fetch-blob` alive and up-to-date even with your busy schedule!

**Comment by RonRadtke** [comment] 2022-02-21 20:04
@jaedontym sorry I had 2 exams and some private issues so I got kinda delayed.
But I think I got it fixed, I will run some more tests tomorrow and if these are fine I'll craft a new release.

**Comment by jaedontym** [comment] 2022-02-22 01:11
@RonRadtke I hope your exams went smoothly and your private issues get resolved. Take care, Ron 🙏

**Comment by RonRadtke** [comment] 2022-02-23 20:44
@jaedontym Update is released

**Comment by RonRadtke** [comment] 2022-02-24 19:37
@HagarAyad the update I released yesterday might fix your problem too. I found a way to reproduce it and fixed it - but I of course can't promise there isn't anything else wrong (e.g. another app modifying the file or so)
@jaedontym thanks! The function should now work as expected and also work on android < 10. With the next update I plan to bring back the old environment paths that should enable being able to write to the public download folder on old devices agian.
@afilp how's it going? everything working well with that part of the lib?

**Comment by afilp** [comment] 2022-02-24 21:42
@RonRadtke Yes, I did not even need that fix, most likely because our users have recent Android versions, but of course it is nice to have this too!

My other (unrelated) problem is when users pick in iOS many heavy images through the picker (8MB each for example) and I show them in a Flatlist. When there are 15+ of them, I have reports that the app is crashing when scrolling to the end of the list.

If you happen to know how to cope with this issue I will greatly appreciate this! I am thinking of using `react-native-resizer`, create duplicate smaller images as thumbnails, to show these in Flatlist, while using  `react-native-blob-util` to upload the original large images one-by-one.

**Closed** 2022-04-25 05:02 UTC
Labels: enhancement, in progress
